#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'
cookbook 'apt'
cookbook 'apache2'
cookbook 'mysql-chef_gem'
cookbook 'database'
cookbook 'mysql'
cookbook 'php'
cookbook 'openssl'
cookbook 'aws'
cookbook 's3cmd'
#cookbook 'hhvm' coming back to this  one
# going to get a working setup before swapping configs around
