#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'
cookbook 'apt'
cookbook 'apache2'
cookbook 'nginx', '~> 2.7.6'
cookbook 'mysqld', '~> 1.0.3'
cookbook 'php', '~> 1.7.2'
cookbook 'php-fpm', '~> 0.7.4'
cookbook 'openssl', '~> 4.4.0'
cookbook 'memcached', '~> 1.8.0'
cookbook 'haproxy', '~> 1.6.6'
cookbook 'aws', '~> 2.7.2'
cookbook 's3cmd', '~> 0.0.1'
cookbook 'gzip', '~> 0.1.0'
cookbook 'hhvm', '~> 0.6.0'