#!/bin/bash
touch /vagrant/chef/s3cfg
echo [default] >> /vagrant/chef/s3cfg
echo access_key = $1 >> /vagrant/chef/s3cfg
echo bucket_location = US >> /vagrant/chef/s3cfg
echo cloudfront_host = cloudfront.amazonaws.com >> /vagrant/chef/s3cfg
echo cloudfront_resource = /2010-07-15/distribution >> /vagrant/chef/s3cfg
echo default_mime_type = binary/octet-stream >> /vagrant/chef/s3cfg
echo delete_removed = False >> /vagrant/chef/s3cfg
echo dry_run = False >> /vagrant/chef/s3cfg
echo encoding = UTF-8 >> /vagrant/chef/s3cfg
echo encrypt = False >> /vagrant/chef/s3cfg
echo follow_symlinks = False >> /vagrant/chef/s3cfg
echo force = False >> /vagrant/chef/s3cfg
echo get_continue = False >> /vagrant/chef/s3cfg
echo gpg_command = /usr/bin/gpg >> /vagrant/chef/s3cfg
echo "gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s" >> /vagrant/chef/s3cfg
echo "gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s" >> /vagrant/chef/s3cfg
echo gpg_passphrase =  >> /vagrant/chef/s3cfg
echo guess_mime_type = True >> /vagrant/chef/s3cfg
echo host_base = s3.amazonaws.com >> /vagrant/chef/s3cfg
echo "host_bucket = %(bucket)s.s3.amazonaws.com" >> /vagrant/chef/s3cfg
echo human_readable_sizes = False >> /vagrant/chef/s3cfg
echo list_md5 = False >> /vagrant/chef/s3cfg
echo log_target_prefix =  >> /vagrant/chef/s3cfg
echo preserve_attrs = True >> /vagrant/chef/s3cfg
echo progress_meter = True >> /vagrant/chef/s3cfg
echo proxy_host =  >> /vagrant/chef/s3cfg
echo proxy_port = 0 >> /vagrant/chef/s3cfg
echo recursive = False >> /vagrant/chef/s3cfg
echo recv_chunk = 4096 >> /vagrant/chef/s3cfg
echo reduced_redundancy = False >> /vagrant/chef/s3cfg
echo secret_key = $2 >> /vagrant/chef/s3cfg
echo send_chunk = 4096 >> /vagrant/chef/s3cfg
echo simpledb_host = sdb.amazonaws.com >> /vagrant/chef/s3cfg
echo skip_existing = False >> /vagrant/chef/s3cfg
echo socket_timeout = 300 >> /vagrant/chef/s3cfg
echo urlencoding_mode = normal >> /vagrant/chef/s3cfg
echo use_https = False >> /vagrant/chef/s3cfg
echo verbosity = WARNING >> /vagrant/chef/s3cfg